export interface CaseStudy {
  id: number;
  category: string;
  title: string;
  location: string;
  equipment: string;
  description: string;
  challenge: string;
  duration: string;
  client: string;
  stats: string;
  image: string;
  youtubeUrl?: string;
  isFeatured: boolean;
}

export const caseStudies: CaseStudy[] = [
  // --- CIVIL CONSTRUCTIONS ---
  {
    id: 1,
    category: "Civil Constructions",
    title: "Dhaka Elevated Expressway Infrastructure",
    location: "Dhaka, Bangladesh",
    client: "Bangladesh Army (ECB-34)",
    equipment: "CPL heavy crawler cranes, piling rigs, transit concrete mixers, and line pumps",
    description: "Massive road and overhead structure development to bypass central city congestion, accelerating national freight transit times.",
    challenge: "Executing heavy overhead lifting and pile caps within active urban traffic channels under strict night shift windows.",
    duration: "28 Months",
    stats: "8.5 km Overhead Spans",
    image: "/images/ourWorks/elevated-expressway.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: true,
  },
  {
    id: 2,
    category: "Civil Constructions",
    title: "DSCC Integrated Road & Drainage Project",
    location: "Dhaka South, Bangladesh",
    client: "Dhaka South City Corporation (DSCC)",
    equipment: "CPL compact excavators, heavy-duty asphalt pavers, and drain shoring systems",
    description: "Simultaneous execution of structural boundary walls, RCC roads, and large-capacity box culvert drainage channels to resolve seasonal waterlogging.",
    challenge: "Extremely high underground utility line density and soft soils requiring custom shoring to prevent road cave-ins.",
    duration: "18 Months",
    stats: "12 km Drainage Laid",
    image: "/images/ourWorks/dhaka-road-project.png",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },
  {
    id: 3,
    category: "Civil Constructions",
    title: "Japanese JV Marine River Bridge Project",
    location: "Chittagong, Bangladesh",
    client: "Japanese Joint Venture Contractor",
    equipment: "CPL marine barges, 150t crawler cranes, deep-water casing piling rigs",
    description: "Anchor foundation piling and girder placement for a heavy-duty highway river bridge linking vital export zones.",
    challenge: "High tidal currents and soft silt beds requiring deep-water concrete caissons anchored 75 meters into the river bed.",
    duration: "36 Months",
    stats: "72 Deep Piles Anchored",
    image: "/images/ourWorks/bridge-project.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },
  {
    id: 4,
    category: "Civil Constructions",
    title: "Sajek-Chimbuk Hilly Highway Construction",
    location: "Bandarban, Bangladesh",
    client: "Bangladesh Army",
    equipment: "CPL tracked excavators, heavy vibratory rollers, and hydraulic rock breakers",
    description: "Carving, stabilizing, and paving a major high-altitude tourist and trade highway corridor through rugged mountainous terrain.",
    challenge: "High-angle slopes and hard granite rock formations requiring continuous heavy rock-breaker hammer operations.",
    duration: "24 Months",
    stats: "32 km Mountain Road",
    image: "/images/ourWorks/mountain-road-project.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },
  {
    id: 5,
    category: "Civil Constructions",
    title: "Cox's Bazar Railway Link Station & Dormitories",
    location: "Cox's Bazar, Bangladesh",
    client: "Chinese Joint Venture Corporation",
    equipment: "CPL batching plant mixers, concrete pumps, and scaffold frames",
    description: "Civil structural frame construction, brickwork, and interior fittings for the modern tourist railway terminal and staff dormitories.",
    challenge: "Saline atmosphere and coastal sandy soil conditions requiring high-performance anti-corrosive concrete mixes.",
    duration: "22 Months",
    stats: "8 Structural Blocks",
    image: "/images/ourWorks/elevated-expressway.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },

  // --- MATERIAL SUPPLY ---
  {
    id: 6,
    category: "Construction Materials Supply",
    title: "Rooppur Nuclear Power Plant Supply Sourcing",
    location: "Ishwardi, Pabna, Bangladesh",
    client: "Russian Government Companies (JSC Atomstroyexport)",
    equipment: "Bulk delivery of stone aggregates, premium grade sand, power tools, safety kits, and metal products",
    description: "Ongoing supply of high-specification construction raw materials, safety tools, and structural accessories to Bangladesh's flagship nuclear facility.",
    challenge: "Meeting strict regulatory standards for material density and safety kits under continuous high-frequency logistics schedules.",
    duration: "Ongoing (Sourcing since 2021)",
    stats: "100% Quality Pass Rate",
    image: "/images/ourWorks/442876.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: true,
  },
  {
    id: 7,
    category: "Construction Materials Supply",
    title: "Matarbari Deep Sea Port Reclamation Supply",
    location: "Matarbari, Cox's Bazar, Bangladesh",
    client: "Japanese Consortium (Sumitomo/Toshiba)",
    equipment: "Coarse stone aggregates, structural grade reinforcing steel rebar, high-tensile cement, and geotextile membranes",
    description: "High-frequency supply chain coordination for marine-adjacent land reclamation and structural foundation concrete elements.",
    challenge: "Ensuring zero-contaminant aggregates that withstand high-salinity marine air and shifting ground pressures.",
    duration: "32 Months (Ongoing)",
    stats: "450k Tons Delivered",
    image: "/images/ourWorks/bridge-project.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },
  {
    id: 8,
    category: "Construction Materials Supply",
    title: "Dhaka Metro Rail Line-6 aggregate Logistics",
    location: "Dhaka, Bangladesh",
    client: "Italian-Thai Development Public Company (ITD)",
    equipment: "Premium Portland cement bulk silos, washed quartz sand, chemical concrete additives, and safety barriers",
    description: "Continuous night-shift logistics supplying concrete ingredients directly to the active Metro Rail precast girder yard.",
    challenge: "Executing tightly regulated transit windows through central Dhaka traffic bottlenecks to prevent concrete cure delays.",
    duration: "24 Months",
    stats: "120k m³ Concrete Sourced",
    image: "/images/ourWorks/dhaka-road-project.png",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },

  // --- EQUIPMENT SERVICES ---
  {
    id: 9,
    category: "Construction Equipment Services",
    title: "Ghorashal Polash Fertilizer Plant Leasing",
    location: "Narsingdi, Bangladesh",
    client: "Chinese Engineering Contractor",
    equipment: "CPL aerial work platforms (MEWPs), heavy truck cranes, and material hoists",
    description: "Leasing a modern fleet of boom lifts and mobile cranes with certified operators to construct steel structures and chemical storage tanks.",
    challenge: "Ensuring zero-error lifting safety limits near high-voltage lines and finished industrial piping zones.",
    duration: "15 Months",
    stats: "4,500+ Operating Hours",
    image: "/images/ourWorks/piling-works.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },
  {
    id: 10,
    category: "Construction Equipment Services",
    title: "Hazrat Shahjalal International Airport Terminal 3 Expansion",
    location: "Dhaka, Bangladesh",
    client: "Mitsubishi-Fujita JV",
    equipment: "CPL heavy crawler cranes, aerial scissor lifts, articulating boom lifts, and telescoping forklifts",
    description: "Fleet leasing of high-altitude MEWPs and mobile cranes for structural steel truss assembly and glass facade installation.",
    challenge: "Operating machinery under strict airfield height limitations and safety clearance guidelines close to active runways.",
    duration: "20 Months",
    stats: "18,000+ Safe Hours",
    image: "/images/ourWorks/elevated-expressway.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },
  {
    id: 11,
    category: "Construction Equipment Services",
    title: "Bangabandhu Sheikh Mujib Railway Bridge Machinery Fleet",
    location: "Sirajganj/Tangail (Jamuna River), Bangladesh",
    client: "Obayashi-TOA Joint Venture",
    equipment: "High-capacity impact pile hammers, 200-ton crawler cranes, heavy material barges, and diesel generators",
    description: "Specialized heavy machinery leasing supporting deep river bed foundation pile driving and structural truss girder placement.",
    challenge: "Maintaining crane operations under strong wind shear forces and river silt bed load shifts.",
    duration: "30 Months",
    stats: "36 Active Heavy Rigs",
    image: "/images/ourWorks/mountain-road-project.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },
  
  // --- ADDITIONAL MATERIALS SUPPLY ---
  {
    id: 12,
    category: "Construction Materials Supply",
    title: "Payra Sea Port Channel Embankment & Geotextiles Sourcing",
    location: "Kalapara, Patuakhali, Bangladesh",
    client: "Payra Port Authority (PPA)",
    equipment: "Woven geotextile bags, geo-tubes, filter fabrics, rock rip-raps, and river-washed coarse sand",
    description: "Providing high-durability marine filter geotextiles and stabilizing sand materials for bank protection and deep channel embankment.",
    challenge: "Sourcing geotextile fabrics that resist underwater drag and high organic degradation in brackish coastal water.",
    duration: "20 Months",
    stats: "350k m² Geotextiles Sourced",
    image: "/images/ourWorks/elevated-expressway.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },
  {
    id: 13,
    category: "Construction Materials Supply",
    title: "Rampal Power Plant Structural Slag Cement Supply",
    location: "Bagerhat, Bangladesh",
    client: "Bharat Heavy Electricals Limited (BHEL)",
    equipment: "Fly-ash resistant Portland composite cement, slag aggregates, and heavy structural steel beams",
    description: "Logistical delivery and sourcing of heavy structural composite concrete ingredients tailored for extreme thermal power plant chimneys and sub-structures.",
    challenge: "Meeting low-heat hydration cement specifications to prevent thermal cracking in massive mass-concrete pours.",
    duration: "26 Months",
    stats: "180k Tons Cement Sourced",
    image: "/images/ourWorks/bridge-project.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },

  // --- ADDITIONAL EQUIPMENT SERVICES ---
  {
    id: 14,
    category: "Construction Equipment Services",
    title: "Karnaphuli River Tunnel Ventilation & Support Fleet",
    location: "Chittagong, Bangladesh",
    client: "China Communications Construction Company (CCCC)",
    equipment: "Confined space ventilation systems, heavy muck trucks, high-capacity water drainage pumps, and scissor lifts",
    description: "Leasing critical support equipment fleet for the underground tunnel boring operations and structural lining installations under the Karnaphuli river bed.",
    challenge: "Providing highly reliable 24/7 continuous operations with zero downtime inside confined, high-pressure underground environments.",
    duration: "24 Months",
    stats: "12,000+ Safe Work Hours",
    image: "/images/ourWorks/piling-works.jpg",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },
  {
    id: 15,
    category: "Construction Equipment Services",
    title: "Dhaka Ashulia Elevated Expressway Rig & Crane Leasing",
    location: "Ashulia, Dhaka, Bangladesh",
    client: "China National Machinery Import & Export Corporation (CMC)",
    equipment: "Heavy rotary pile drilling rigs, hydraulic drills, 100t crawler cranes, and heavy-duty generators",
    description: "Leasing pile drilling rigs and heavy crawler cranes for overhead pier construction along the high-traffic Ashulia corridor.",
    challenge: "Operating heavy piling drills in close proximity to active gas lines and high-voltage transmission grids.",
    duration: "18 Months (Ongoing)",
    stats: "15 Heavy Rigs Deployed",
    image: "/images/ourWorks/dhaka-road-project.png",
    youtubeUrl: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    isFeatured: false,
  },
];
